generous_book_names = {
	"Genesis": "Genesis",
	"Gen": "Genesis",
	"Exodus": "Exodus",
	"Exod": "Exodus",
	"Ex": "Exodus",
	"Leviticus": "Leviticus",
	"Lev": "Leviticus",
	"Numbers": "Numeri",
	"Num": "Numeri",
	"Deuteronomy": "Deuteronomium",
	"Deut": "Deuteronomium",
	"Joshua": "Josua",
	"Josh": "Josua",
	"Judges": "Judices",
	"Judg": "Judices",
	"1 Samuel": "Samuel_I",
	"1_Samuel": "Samuel_I",
	"1Sam": "Samuel_I",
	"1 Sam": "Samuel_I",
	"2 Samuel": "Samuel_II",
	"2_Samuel": "Samuel_II",
	"2Sam": "Samuel_II",
	"2 Sam": "Samuel_II",
	"1 Kings": "Reges_I",
	"1_Kings": "Reges_I",
	"1Kgs": "Reges_I",
	"1 Kgs": "Reges_I",
	"2 Kings": "Reges_II",
	"2_Kings": "Reges_II",
	"2Kgs": "Reges_II",
	"2 Kgs": "Reges_II",
	"Isaiah": "Jesaia",
	"Isa": "Jesaia",
	"Jeremiah": "Jeremia",
	"Jer": "Jeremia",
	"Ezekiel": "Ezechiel",
	"Ezek": "Ezechiel",
	"Hosea": "Hosea",
	"Hos": "Hosea",
	"Joel": "Joel",
	"Amos": "Amos",
	"Obadiah": "Obadia",
	"Obad": "Obadia",
	"Ob": "Obadia",
	"Jonah": "Jona",
	"Jon": "Jona",
	"Micah": "Micha",
	"Mic": "Micha",
	"Nahum": "Nahum",
	"Nah": "Nahum",
	"Habakkuk": "Habakuk",
	"Hab": "Habakuk",
	"Zephaniah": "Zephania",
	"Zeph": "Zephania",
	"Haggai": "Haggai",
	"Hag": "Haggai",
	"Zechariah": "Sacharia",
	"Zech": "Sacharia",
	"Malachi": "Maleachi",
	"Mal": "Maleachi",
	"Psalms": "Psalmi",
	"Ps": "Psalmi",
	"Pss": "Psalmi",
	"Job": "Iob",
	"Proverbs": "Proverbia",
	"Prov": "Proverbia",
	"Ruth": "Ruth",
	"Song of Solomon": "Canticum",
	"Song_of_Solomon": "Canticum",
	"Song of Songs": "Canticum",
	"Song_of_Songs": "Canticum",
	"Song_of_songs": "Canticum",
	"Songs": "Canticum",
	"Cant": "Canticum",
	"Ecclesiastes": "Ecclesiastes",
	"Eccl": "Ecclesiastes",
	"Lamentations": "Threni",
	"Lam": "Threni",
	"Esther": "Esther",
	"Esth": "Esther",
	"Daniel": "Daniel",
	"Dan": "Daniel",
	"Ezra": "Esra",
	"Nehemiah": "Nehemia",
	"Neh": "Nehemia",
	"1Chr": "Chronica_I",
	"1 Chr": "Chronica_I",
	"1Chron": "Chronica_I",
	"1 Chronicles": "Chronica_I",
	"1_Chronicles": "Chronica_I",
	"2Chr": "Chronica_II",
	"2 Chr": "Chronica_II",
	"2Chron": "Chronica_II",
	"2 Chronicles": "Chronica_II",
	"2_Chronicles": "Chronica_II",
}
book_to_index = {
	"Genesis": 1,
	"Exodus": 2,
	"Leviticus": 3,
	"Numeri": 4,
	"Deuteronomium": 5,
	"Josua": 6,
	"Judices": 7,
	"Ruth": 8,
	"Samuel_I": 9,
	"Samuel_II": 10,
	"Reges_I": 11,
	"Reges_II": 12,
	"Chronica_I": 13,
	"Chronica_II": 14,
	"Esra": 15,
	"Nehemia": 16,
	"Esther": 17,
	"Iob": 18,
	"Psalmi": 19,
	"Proverbia": 20,
	"Ecclesiastes": 21,
	"Canticum": 22,
	"Jesaia": 23,
	"Jeremia": 24,
	"Threni": 25,
	"Ezechiel": 26,
	"Daniel": 27,
	"Hosea": 28,
	"Joel": 29,
	"Amos": 30,
	"Obadia": 31,
	"Jona": 32,
	"Micha": 33,
	"Nahum": 34,
	"Habakuk": 35,
	"Zephania": 36,
	"Haggai": 37,
	"Sacharia": 38,
	"Maleachi": 39,
}
# SBL Abbreviations
abbreviated_book_names = {
	"Genesis": "Gen",
	"Exodus": "Exod",
	"Leviticus": "Lev",
	"Numeri": "Num",
	"Deuteronomium": "Deut",
	"Josua": "Josh",
	"Judices": "Judg",
	"Samuel_I": "1 Sam",
	"Samuel_II": "2 Sam",
	"Reges_I": "1 Kgs",
	"Reges_II": "2 Kgs",
	"Jesaia": "Isa",
	"Jeremia": "Jer",
	"Ezechiel": "Ezek",
	"Hosea": "Hos",
	"Joel": "Joel",
	"Amos": "Amos",
	"Obadia": "Obad",
	"Jona": "Jonah",
	"Micha": "Mic",
	"Nahum": "Nah",
	"Habakuk": "Hab",
	"Zephania": "Zeph",
	"Haggai": "Hag",
	"Sacharia": "Zech",
	"Maleachi": "Mal",
	"Psalmi": "Ps",
	"Iob": "Job",
	"Proverbia": "Prov",
	"Ruth": "Ruth",
	"Canticum": "Song",
	"Ecclesiastes": "Eccl",
	"Threni": "Lam",
	"Esther": "Esth",
	"Daniel": "Dan",
	"Esra": "Ezra",
	"Nehemia": "Neh",
	"Chronica_I": "1 Chr",
	"Chronica_II": "2 Chr",
}

def generous_name(book_name):
	return generous_book_names[book_name] if book_name in generous_book_names else book_name

def book_index(book_name):
	return int(book_to_index[generous_name(book_name)])
	# return int(book_to_index[book_name])

def book_abbreviation(book_name):
	return abbreviated_book_names[generous_name(book_name)]
