generous_book_names = {
	"Genesis": "Genesis",
	"Gen": "Genesis",
	"Exodus": "Exodus",
	"Ex": "Exodus",
	"Leviticus": "Leviticus",
	"Lev": "Leviticus",
	"Numbers": "Numeri",
	"Num": "Numeri",
	"Deuteronomy": "Deuteronomium",
	"Deut": "Deuteronomium",
	"Joshua": "Josua",
	"Josh": "Josua",
	"Judges": "Judices",
	"Judg": "Judices",
	"1 Samuel": "Samuel_I",
	"1_Samuel": "Samuel_I",
	"1Sam": "Samuel_I",
	"2 Samuel": "Samuel_II",
	"2_Samuel": "Samuel_II",
	"2Sam": "Samuel_II",
	"1 Kings": "Reges_I",
	"1_Kings": "Reges_I",
	"1Kgs": "Reges_I",
	"2 Kings": "Reges_II",
	"2_Kings": "Reges_II",
	"2Kgs": "Reges_II",
	"Isaiah": "Jesaia",
	"Isa": "Jesaia",
	"Jeremiah": "Jeremia",
	"Jer": "Jeremia",
	"Ezekiel": "Ezechiel",
	"Ez": "Ezechiel",
	"Hosea": "Hosea",
	"Hos": "Hosea",
	"Joel": "Joel",
	"Amos": "Amos",
	"Obadiah": "Obadia",
	"Ob": "Obadia",
	"Jonah": "Jona",
	"Jon": "Jona",
	"Micah": "Micha",
	"Mic": "Micha",
	"Nahum": "Nahum",
	"Nah": "Nahum",
	"Habakkuk": "Habakuk",
	"Hab": "Habakuk",
	"Zephaniah": "Zephania",
	"Zeph": "Zephania",
	"Haggai": "Haggai",
	"Hag": "Haggai",
	"Zechariah": "Sacharia",
	"Zech": "Sacharia",
	"Malachi": "Maleachi",
	"Mal": "Maleachi",
	"Psalms": "Psalmi",
	"Ps": "Psalmi",
	"Job": "Iob",
	"Proverbs": "Proverbia",
	"Prov": "Proverbia",
	"Ruth": "Ruth",
	"Song of Solomon": "Canticum",
	"Song_of_Solomon": "Canticum",
	"Song of Songs": "Canticum",
	"Song_of_Songs": "Canticum",
	"Songs": "Canticum",
	"Ecclesiastes": "Ecclesiastes",
	"Eccl": "Ecclesiastes",
	"Lamentations": "Threni",
	"Lam": "Threni",
	"Esther": "Esther",
	"Esth": "Esther",
	"Daniel": "Daniel",
	"Dan": "Daniel",
	"Ezra": "Esra",
	"Nehemiah": "Nehemia",
	"Neh": "Nehemia",
	"1 Chronicles": "Chronica_I",
	"1_Chronicles": "Chronica_I",
	"1Chron": "Chronica_I",
	"2 Chronicles": "Chronica_II",
	"2_Chronicles": "Chronica_II",
	"2Chron": "Chronica_II",
}
book_to_index = {
	"Genesis": 1,
	"Exodus": 2,
	"Leviticus": 3,
	"Numbers": 4,
	"Deuteronomy": 5,
	"Joshua": 6,
	"Judges": 7,
	"Ruth": 8,
	"1 Samuel": 9,
	"1_Samuel": 9,
	"2 Samuel": 10,
	"2_Samuel": 10,
	"1 Kings": 11,
	"1_Kings": 11,
	"2 Kings": 12,
	"2_Kings": 12,
	"1 Chronicles": 13,
	"1_Chronicles": 13,
	"2 Chronicles": 14,
	"2_Chronicles": 14,
	"Ezra": 15,
	"Nehemiah": 16,
	"Esther": 17,
	"Job": 18,
	"Psalms": 19,
	"Proverbs": 20,
	"Ecclesiastes": 21,
	"Song of Solomon": 22,
	"Song_of_Solomon": 22,
	"Song_of_songs": 22,
	"Isaiah": 23,
	"Jeremiah": 24,
	"Lamentations": 25,
	"Ezekiel": 26,
	"Daniel": 27,
	"Hosea": 28,
	"Joel": 29,
	"Amos": 30,
	"Obadiah": 31,
	"Jonah": 32,
	"Micah": 33,
	"Nahum": 34,
	"Habakkuk": 35,
	"Zephaniah": 36,
	"Haggai": 37,
	"Zechariah": 38,
	"Malachi": 39
}

def generous_name(book_name):
	return generous_book_names[book_name] if book_name in generous_book_names else book_name


def book_index(book_name):
	return int(book_to_index[book_name])
